export enum CardMoveType {
  VALID = "VALID",
  INVALID = "INVALID",
  INVALID_ON_CREATE = "INVALID_ON_CREATE",
  INVALID_SILVER_BULLET_ON_CREATE = "INVALID_SILVER_BULLET_ON_CREATE",
  INVALID_WIP_CHANGE = "INVALID_WIP_CHANGE",
}
