export enum MemberType {
  DEVELOPER = "DEVELOPER",
  KANBAN_MASTER = "KANBAN_MASTER",
  PRODUCT_OWNER = "PRODUCT_OWNER",
  DEVELOPER_AND_KANBAN_MASTER = "DEVELOPER_AND_KANBAN_MASTER",
  DEVELOPER_AND_PRODUCT_OWNER = "DEVELOPER_AND_PRODUCT_OWNER"
}
