export class MemberType {
  static DEVELOPER = "DEVELOPER";
  static KANBAN_MASTER = "KANBAN_MASTER";
  static PRODUCT_OWNER = "PRODUCT_OWNER";
  static DEVELOPER_AND_KANBAN_MASTER = "DEVELOPER_AND_KANBAN_MASTER";
  static DEVELOPER_AND_PRODUCT_OWNER = "DEVELOPER_AND_PRODUCT_OWNER";
}
